name: On Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - name: Use Node LTS âœ¨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies ğŸ“¦ï¸
        run: pnpm install --frozen-lockfile

      - name: Set version to release tag ğŸ“
        shell: bash
        run:
          pnpm version from-git --no-commit-hooks --no-git-tag-version
          --allow-same-version

      - name: Push version changes to main branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: release ${{ github.event.release.tag_name }}'
          branch: ${{ github.event.repository.default_branch }}
          file_pattern: package.json

      - name: Build ğŸ—ï¸
        run: pnpm build

      - name: Prepare release
        env:
          FILENAME: bjerk-chrome-extension-${{ github.event.release.tag_name }}
        run: |
          mv dist/ ${{ env.FILENAME }}/
          zip -r "${{ env.FILENAME }}.zip" ${{ env.FILENAME }}/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bjerk-chrome-extension-${{ github.event.release.tag_name }}.zip
